apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bulk-resolve-hb-faults
  namespace: molecule-<NAMESPACE>
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-user"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-env-config.env: "secrets/mfunctions-<VAULTSPACE>/env-config"
        vault.hashicorp.com/agent-inject-template-env-config.env: |
          {{- with secret "secrets/mfunctions-<VAULTSPACE>/env-config" -}}
          {{ range $key, $value := .Data -}}
          export {{ $key }}="{{ $value }}"
          {{ end }}
          {{- end -}}
    spec:      
      imagePullSecrets:
        - name: docker-json
      serviceAccountName: vault-auth
      containers:
        - image: registry.molecule.io/m.functions/bulk-resolve-hb-faults:<VERSION>
          name: bulk-resolve-hb-faults
          command: ["/bin/bash", "-ec"]
          args: ["source /vault/secrets/env-config.env &&
                  exec gunicorn --bind :$PORT --workers 1 --threads 8 service:app"]
          env:
          - name: honeybadger_check_in
            value: https://api.honeybadger.io/v1/check_in/aNIj0p
