name: Build and Push Knative Services Images

on:
  push:
    branches:
      - main

jobs:
  build-simple-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Simple Service
      uses: docker/build-push-action@v2
      with:
        context: ./samples/simple-service
        file: ./samples/simple-service/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/simple-service:latest
  build-event-handler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Event Handler Service
      uses: docker/build-push-action@v2
      with:
        context: ./samples/event-handler
        file: ./samples/event-handler/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/event-handler:latest
  build-event-subscriber:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Event Subscriber Service
      uses: docker/build-push-action@v2
      with:
        context: ./samples/event-subscriber
        file: ./samples/event-subscriber/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/event-subscriber:latest
  build-event-subscriber-with-sink:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Event Subscriber Service
      uses: docker/build-push-action@v2
      with:
        context: ./samples/event-subscriber-with-sink
        file: ./samples/event-subscriber-with-sink/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/event-subscriber-with-sink:latest        